test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# give the S3 configuration a conventional name (`amazon`) and
# reference it from the production environment.  this makes it easier to
# switch between services in development or debugging.
amazon: 
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: us-east-1
  bucket: ruby-assignment

production:
  <<: *amazon
